{
    'name': 'Laboratorio',
    'version': '15.0.1.0.0',
    'summary': 'Genera protocolos de control analítico de aguas',
    'category': 'Uncategorized',
    'author': 'RMF',
    'maintainer': 'RMF',
    'website': '',
    'license': 'AGPL-3',
    'depends': [
        'mail',
        'web_widget_x2many_2d_matrix',
        'industry_fsm_report',
        'mail_mobile',
        'contacts',  # si bien no es necesaria la  agregamos porque sin esta no hay acceso a res.partner
    ],
    'data': [
        'security/ir.model.access.csv',
        'reports/worksheet_control_analitico_agua_report.xml',
        'reports/fsm_vatten_report.xml',
        'views/worksheet_control_analitico_agua_views.xml',
        'data/data_chemical_parameters.xml',
        'data/laboratory_order_sequence.xml',
        'data/laboratory_mail_template_fsm.xml',
        'data/worksheet_template_data.xml',
        'data/vatten_mail_template.xml',
        'views/res_partner.xml',
        'views/view_chemical_parameters.xml',
        'views/view_muestras_medidas.xml',
        'views/menu.xml',
        'views/project_task.xml',
        'data/fsm_report_data.xml',
    ],
    'demo': [
        'data/fsm_report_demo.xml',
        'data/laboratory_demo.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
