from . import x_seguimientos
from . import x_seguimientos_stage
from . import account_analytic_line
from . import account_move
from . import crm_lead
from . import helpdesk_tag
from . import helpdesk_ticket
from . import hr_attendance
from . import hr_contract
from . import hr_employee
from . import hr_expense
from . import hr_leave
from . import hr_employee_skill
from . import maintenance_equipment
from . import project_project
from . import project_task
from . import purchase_order
from . import purchase_request
from . import res_partner
from . import res_users
from . import sale_subscription
from . import sale_order
from . import purchase_request_line
