# -*- coding: utf-8 -*-
{
    'name': 'personalizations_brunetti',
    'version': '11.0.1.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account',
        'account_payment_group',
        'base',
        'calendar',
        'crm',
        'delivery',
        'helpdesk',
        'inter_company_rules',
        'l10n_ar_aeroo_stock',
        'mass_editing',
        'product',
        'purchase',
        'report_aeroo',
    ],
    'data': [
        'views/account_invoice_views.xml',
        'views/adhoc_module_category_views.xml',
        'views/crm_lead_views.xml',
        'views/crm_stage_views.xml',
        'views/product_template_views.xml',
        'views/purchase_order_views.xml',
        'data/ir_actions_act_window.xml',
        'report/ir_actions_report.xml',
        'data/ir_cron.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'security/ir_rule.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
