{
    'name': 'personalizations_adhoc',
    'version': "15.0.1.1.0",
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'hr_timesheet',
        'hr_contract',
        'helpdesk',
    ],
    'data': [
        'views/hr_contract_views.xml',
        'views/adhoc_product_views.xml',
        'views/adhoc_product_menus.xml',
        'views/hr_job_views.xml',
        'views/hr_salary_category_views.xml',
        'views/hr_seniority_views.xml',
        'views/helpdesk_ticket_views.xml',
        'data/hr_salary_category_data.xml',
        'data/hr_seniority_data.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [
        'demo/adhoc_product_demo.xml',
        'demo/hr_department_demo.xml',
        'demo/hr_employee_demo.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'OPL-1',
}
