from . import x_partner_project
from . import x_project
from . import res_partner
from . import product_template
from . import stock_picking
from . import product_attribute_value
from . import sale
from . import res_user
from . import account_move
