from . import hr_contract
from . import hr_salary_category
from . import hr_seniority
from . import hr_job
from . import hr_job_seniority
from . import hr_department
from . import hr_employee
from . import adhoc_product
from . import helpdesk_ticket
from . import project_task
