from . import stock_request_order
from . import res_users
from . import purchase_requisition
from . import purchase_requisition_line
from . import mail_compose_message
from . import product_product
from . import stock_move
from . import fleet_vehicle_cost
from . import purchase_request
from . import stock_location
