# -*- coding: utf-8 -*-
{
    'name': 'personalizations_robertocala',
    'version': '11.0.1.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account',
        'account_ux',
        'base',
        'board',
        'delivery',
        'l10n_ar_aeroo_einvoice',
        'l10n_ar_aeroo_stock',
        'note',
        'price_security',
        'product',
        'product_planned_price',
        'product_replenishment_cost',
        'purchase',
        'report_aeroo',
        'sale',
        'stock',
        'stock_picking_labels',
        'website_sale',
    ],
    'data': [
        'security/res_groups.xml',
        'views/account_invoice_views.xml',
        'views/product_product_views.xml',
        'views/product_template_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/stock_move_line_views.xml',
        'data/ir_actions_act_window.xml',
        'report/ir_actions_report.xml',
        'data/ir_cron.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
