from . import product_template
from . import product_supplierinfo
from . import product_abstract
from . import product_image
from . import product_attribute
from . import res_partner
from . import account_followup_report
from . import uom_uom
from . import stock_book
from . import purchase_order_line
from . import product_pricelist
from . import product_pricelist_item
from . import stock_move_line
from . import stock_quant
from . import sale_order
