from . import x_account_payment_group_stage
from . import x_instaladores
from . import x_res_country_state_department
from . import x_tipoinsta
from . import account_check
from . import account_payment_group
from . import document_page
from . import helpdesk_ticket
from . import product_pack_line
from . import product_pricelist_item
from . import product_template
from . import project_task
from . import purchase_order
from . import purchase_order_line
from . import purchase_request
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import stock_picking