# -*- coding: utf-8 -*-
{
    'name': 'personalizations_edicioneslogos',
    'version': '11.0.1.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account',
        'account_analytic_default',
        'account_reports',
        'base',
        'bi_sql_editor',
        'board',
        'crm',
        'database_cleanup',
        'delivery',
        'ks_dashboard_ninja',
        'l10n_ar_aeroo_stock',
        'l10n_ar_stock',
        'mail',
        'mail_push',
        'mass_editing',
        'portal_sale_distributor',
        'product',
        'product_catalog_aeroo_report',
        'report_aeroo',
        'sale',
        'sales_team',
        'sql_request_abstract',
        'stock',
        'website',
    ],
    'data': [
        'views/account_voucher_receipt_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'views/x_bi_sql_view_logos_invoice_analysis_views.xml',
        'views/x_partner_project_views.xml',
        'views/x_project_views.xml',
        'data/ir_actions_act_window.xml',
        'report/ir_actions_report.xml',
        'data/ir_cron.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
