from . import x_account_overdue_type
from . import x_hr_applicant_appraisal
from . import x_motive_rejected_proposal
from . import x_no_vacancy_specification_motive
from . import x_res_partner_emergency_contact
from . import crm_lead
from . import crm_team
from . import hr_applicant
from . import hr_departure_wizard
from . import hr_employee
from . import hr_job
from . import maintenance_request
from . import payment_token
from . import res_company
from . import res_partner
from . import sale_subscription
from . import survey_survey
from . import survey_page
from . import survey_user_input_line
from . import survey_user_input
from . import academic_group
from . import academic_level
from . import academic_section
from . import account_payment_group
