version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    target_branch: "13.0"
    default_reviewers:
      - "azacchino"
      - "jjscarafia"
    default_assignees:
      - "azacchino"
    default_labels:
      - "dependencies"
      - "dependabot"
