from . import x_product_autor
from . import x_product_categoria
from . import x_product_editorial
from . import x_product_familia
from . import x_product_language
from . import x_product_subcategoria
from . import x_product_version
from . import x_res_partner_stage
from . import account_debt_line
from . import account_invoice
from . import account_invoice_line
from . import product_pricelist
from . import product_pricelist_item
from . import product_template
from . import purchase_order_line
from . import res_company
from . import res_partner
from . import sale_order_line
from . import sale_order
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import stock_request_order
