{
    'name': 'personalizations_tg2',
    'version': '13.0.1.0.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account_analytic_parent',
        'helpdesk',
        'purchase',
        'hr_timesheet',
        'timesheet_grid',
        'report_aeroo',
    ],
    'data': [
        'views/account_analytic_account_views.xml',
        'views/account_analytic_line_views.xml',
        'views/hr_employee_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'report/ir_actions_report.xml',
        'security/ir_rule.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'OPL-1',
}
