# -*- coding: utf-8 -*-
{
    'name': 'personalizations_tg2',
    'version': '11.0.1.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account',
        'account_analytic_parent',
        'analytic',
        'base',
        'delivery',
        'helpdesk',
        'hr',
        'hr_timesheet',
        'l10n_ar_aeroo_stock',
        'mass_editing',
        'purchase',
        'report_aeroo',
        'sale',
        'sale_timesheet',
        'stock',
        'timesheet_grid',
    ],
    'data': [
        'views/account_analytic_account_views.xml',
        'views/account_analytic_line_views.xml',
        'views/hr_employee_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
        'data/ir_actions_act_window.xml',
        'report/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/base_automation.xml',
        'security/ir_rule.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
