{
    'name': 'personalizations_sba',
    'version': '11.0.2.0',
    'category': 'Personalizations',
    'author': 'ADHOC SA',
    'depends': [
        'account_analytic_default',
        'account_debt_management',
        'hr_expense',
        'l10n_ar_aeroo_einvoice',
        'l10n_ar_aeroo_stock',
        'purchase',
        'sale_ux',
        'stock_ux',
        'helpdesk',
    ],
    'data': [
        'security/personalizations_sba_security.xml',
        'views/account_debt_line_views.xml',
        'views/account_invoice_views.xml',
        'views/hr_expense_views.xml',
        'views/hr_expense_sheet_views.xml',
        'views/product_pricelist_views.xml',
        'views/product_pricelist_item_views.xml',
        'views/product_product_views.xml',
        'views/product_template_views.xml',
        'views/purchase_order_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_bank_views.xml',
        'views/sale_order_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_quant_views.xml',
        'wizards/stock_return_picking_views.xml',
        'views/x_product_autor_views.xml',
        'views/x_product_categoria_views.xml',
        'views/x_product_editorial_views.xml',
        'views/x_product_familia_views.xml',
        'views/x_product_language_views.xml',
        'views/x_product_subcategoria_views.xml',
        'views/x_product_version_views.xml',
        'views/x_res_partner_stage_views.xml',
        'data/ir_actions_act_window.xml',
        'report/ir_actions_report.xml',
        'data/ir_cron.xml',
        'data/ir_ui_menu.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
    ],
    'application': False,
    'license': 'OPL-1',
}
