from . import x_controles_remitos_diarios
from . import x_devolucion_tags_devolucion_tags
from . import x_origen_tags
from . import x_stock_picking_setstate
from . import x_stock_breakout
from . import res_partner
from . import account_invoice
from . import account_move_line
from . import account_payment_group
from . import mail_mass_mailing_contact
from . import mgmtsystem_nonconformity
from . import mis_report_instance
from . import product_attribute
from . import product_attribute_line
from . import product_attribute_template
from . import product_pricelist
from . import product_product
from . import product_public_category
from . import product_supplierinfo
from . import product_template
from . import project_tags
from . import project_task
from . import purchase_order
from . import purchase_order_line
from . import res_partner_industry
from . import sale_order
from . import sale_order_line
from . import sale_order_type
from . import stock_picking_batch
from . import stock_inventory
from . import stock_location
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_request_order
from . import stock_warehouse_orderpoint
